import type { Issue } from "@/components/issues/types";

export const mockIssues: Issue[] = [
	{
		id: 1,
		title: "Add dark mode support",
		repository: "user/repo-one",
		number: 123,
		state: "open",
		comments: 5,
		createdAt: "2026-04-20",
		labels: ["enhancement", "ui"],
		url: "#",
	},
	{
		id: 2,
		title: "Fix authentication bug",
		repository: "user/repo-two",
		number: 456,
		state: "open",
		comments: 12,
		createdAt: "2026-04-18",
		labels: ["bug", "priority"],
		url: "#",
	},
	{
		id: 3,
		title: "Update dependencies",
		repository: "user/repo-one",
		number: 124,
		state: "open",
		comments: 2,
		createdAt: "2026-04-15",
		labels: ["maintenance"],
		url: "#",
	},
	{
		id: 4,
		title: "Improve performance",
		repository: "org/repo-three",
		number: 789,
		state: "open",
		comments: 8,
		createdAt: "2026-04-22",
		labels: ["performance", "enhancement"],
		url: "#",
	},
	{
		id: 5,
		title: "Add API documentation",
		repository: "org/repo-three",
		number: 790,
		state: "open",
		comments: 3,
		createdAt: "2026-04-19",
		labels: ["documentation"],
		url: "#",
	},
	{
		id: 6,
		title: "Refactor authentication module",
		repository: "user/repo-two",
		number: 457,
		state: "open",
		comments: 7,
		createdAt: "2026-04-17",
		labels: ["refactor"],
		url: "#",
	},
	{
		id: 7,
		title: "Add unit tests for API endpoints",
		repository: "org/repo-three",
		number: 791,
		state: "open",
		comments: 4,
		createdAt: "2026-04-16",
		labels: ["testing"],
		url: "#",
	},
	{
		id: 8,
		title: "Fix mobile responsiveness",
		repository: "user/repo-one",
		number: 125,
		state: "open",
		comments: 9,
		createdAt: "2026-04-14",
		labels: ["bug", "mobile"],
		url: "#",
	},
];

export const mockPinnedIssues: Issue[] = [
	{
		id: 1,
		title: "Add dark mode support",
		repository: "user/repo-one",
		number: 123,
		state: "open",
		comments: 5,
		createdAt: "2026-04-20",
		labels: ["enhancement", "ui"],
		url: "#",
	},
	{
		id: 3,
		title: "Update dependencies",
		repository: "user/repo-one",
		number: 124,
		state: "open",
		comments: 2,
		createdAt: "2026-04-15",
		labels: ["maintenance"],
		url: "#",
	},
	{
		id: 2,
		title: "Fix authentication bug",
		repository: "user/repo-two",
		number: 456,
		state: "open",
		comments: 12,
		createdAt: "2026-04-18",
		labels: ["bug", "priority"],
		url: "#",
	},
	{
		id: 4,
		title: "Improve performance",
		repository: "org/repo-three",
		number: 789,
		state: "open",
		comments: 8,
		createdAt: "2026-04-22",
		labels: ["performance", "enhancement"],
		url: "#",
	},
	{
		id: 5,
		title: "Add API documentation",
		repository: "org/repo-three",
		number: 790,
		state: "open",
		comments: 3,
		createdAt: "2026-04-19",
		labels: ["documentation"],
		url: "#",
	},
];
