/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RepositoriesRouteImport } from './routes/repositories'
import { Route as IssuesRouteImport } from './routes/issues'
import { Route as IndexRouteImport } from './routes/index'

const RepositoriesRoute = RepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesRoute = IssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/issues': typeof IssuesRoute
  '/repositories': typeof RepositoriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/issues': typeof IssuesRoute
  '/repositories': typeof RepositoriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/issues': typeof IssuesRoute
  '/repositories': typeof RepositoriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/issues' | '/repositories'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/issues' | '/repositories'
  id: '__root__' | '/' | '/issues' | '/repositories'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IssuesRoute: typeof IssuesRoute
  RepositoriesRoute: typeof RepositoriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/repositories': {
      id: '/repositories'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof RepositoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues': {
      id: '/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof IssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IssuesRoute: IssuesRoute,
  RepositoriesRoute: RepositoriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
